version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ismaster')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Uncomment this if you want to run the Spring Boot app in Docker too
  # ecommerce-app:
  #   build: .
  #   container_name: ecommerce-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #     SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ecommerce
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongodb_data: